export default [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'Fort Worth',
  'Columbus',
  'San Francisco',
  'Charlotte',
  'Indianapolis',
  'Seattle',
  'Denver',
  'Washington',
  'Boston',
  'Nashville',
  'El Paso',
  'Detroit',
  'Memphis',
  'Portland',
  'Oklahoma City',
  'Las Vegas',
  'Louisville',
  'Baltimore',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Mesa',
  'Sacramento',
  'Atlanta',
  'Kansas City',
  'Colorado Springs',
  'Miami',
  'Raleigh',
  'Omaha',
  'Long Beach',
  'Virginia Beach',
  'Oakland',
  'Minneapolis',
  'Tulsa',
  'Wichita',
  'New Orleans',
  'Arlington',
  'Tampa',
  'Santa Ana',
  'St. Louis',
  'Pittsburgh',
  'Corpus Christi',
  'Riverside',
  'Cincinnati',
  'Lexington',
  'Anchorage',
  'Stockton',
  'Toledo',
  'Saint Paul',
  'Newark',
  'Greensboro',
  'Buffalo',
  'Plano',
  'Lincoln',
  'Henderson',
  'Fort Wayne',
  'Jersey City',
  'Saint Petersburg',
  'Chula Vista',
  'Norfolk',
  'Orlando',
  'Chandler',
  'Laredo',
  'Madison',
  'Winston-Salem',
  'Lubbock',
  'Baton Rouge',
  'Durham',
  'Garland',
  'Glendale',
  'Reno',
  'Hialeah',
  'Chesapeake',
  'Scottsdale',
  'North Las Vegas',
  'Irving',
  'Fremont',
  'Irvine',
  'Birmingham',
  'Rochester',
  'San Bernardino',
  'Spokane',
  'Gilbert',
];
