export default [
  'Apple',
  'Banana',
  'Cherry',
  'Date',
  'Elderberry',
  'Fig',
  'Grape',
  'Honeydew',
  'Imbe',
  'Jackfruit',
  'Kiwi',
  'Lemon',
  'Mango',
  'Nectarine',
  'Orange',
  'Pineapple',
  'Quince',
  'Raspberry',
  'Strawberry',
  'Tangerine',
  'Ugli fruit',
  'Vanilla bean',
  'Watermelon',
  'Xigua',
  'Yellow watermelon',
  'Zucchini',
  'Apricot',
  'Blackberry',
  'Clementine',
  'Dragonfruit',
  'Eggfruit',
  'Feijoa',
  'Guava',
  'Honeyberry',
  'Ice cream bean',
  'Jabuticaba',
  'Kumquat',
  'Lime',
  'Mulberry',
  'Nashi pear',
  'Olive',
  'Peach',
  'Pear',
  'Quandong',
  'Rambutan',
  'Starfruit',
  'Apricot',
  'Avocado',
  'Blackcurrant',
  'Blueberry',
  'Boysenberry',
  'Cantaloupe',
  'Cranberry',
  'Durian',
  'Eggplant',
  'Fruit cocktail',
  'Grapefruit',
  'Honeycrisp apple',
  'Jujube',
  'Kiwi berry',
  'Lemonade fruit',
  'Mandarin orange',
  'Nectar',
  'Ogen melon',
  'Passion fruit',
  'Pomelo',
  'Queen anne cherry',
  'Raisin',
  'Satsuma',
  'Tangelo',
  'Ugni',
  'Victoria plum',
  'White currant',
  'Ximenia',
  'Yuzu',
  'Zinfandel grape',
  'Almond',
  'Breadfruit',
  'Coconut',
  'Damson',
  'Elderflower',
  'Figs',
  'Gourds',
  'Hawthorn',
  'Indian gooseberry',
  'Jambul',
  'Kiwi fruit',
  'Loquat',
  'Mamey sapote',
  'Nance',
  'Olallieberry',
  'Papaya',
  'Quince',
  'Rose apple',
  'Strawberry tree fruit',
  'Tamarind',
  'Ulluco',
  'Wax apple',
  'Yellow passion fruit',
  'Zucchini flower',
];
