export default [
  'Jaws',
  'Psycho',
  'Alien',
  'Up',
  'Memento',
  'Whiplash',
  'Her',
  'Moonlight',
  'Birdman',
  'Boyhood',
  'Once',
  'Amélie',
  'Crash',
  'Moon',
  'Drive',
  'Fargo',
  'Get Out',
  'Deadpool',
  'Juno',
  'The Lobster',
  'Hunt for the Wilderpeople',
  'The Grand Budapest Hotel',
  'Room',
  'The Big Sick',
  'Donnie Darko',
  'Little Miss Sunshine',
  '500 Days of Summer',
  'Eternal Sunshine of the Spotless Mind',
  'Lost in Translation',
  'The Florida Project',
  'Lady Bird',
  'Frances Ha',
  'The Darjeeling Limited',
  'Fantastic Mr. Fox',
  'Scott Pilgrim vs. the World',
  'The Blair Witch Project',
  'Paranormal Activity',
  'The Babadook',
  'It Follows',
  'The Witch',
  'The Invitation',
  'Hush',
  'Creep',
  'The Purge',
  'Scream',
  'The Others',
  'The Sixth Sense',
  'Insidious',
  'Sinister',
  'The Visit',
  'Split',
  'Unbreakable',
  'Signs',
  'The Village',
  'The Happening',
  'The Mist',
  'The Descent',
  'The Shallows',
  'Open Water',
  'Gravity',
  'Apollo 13',
  'The Martian',
  'Cast Away',
  '127 Hours',
  'Buried',
  'Locke',
  'The Theory of Everything',
  'The Imitation Game',
  'Sicario',
  'No Country for Old Men',
  'There Will Be Blood',
  'The Departed',
  'Gone Girl',
  'The Girl with the Dragon Tattoo',
  'The Social Network',
  "The King's Speech",
  'Little Women',
  'The Breakfast Club',
  'Sixteen Candles',
  "Ferris Bueller's Day Off",
  'Dead Poets Society',
  'Good Will Hunting',
  'Election',
];
