export default [
  'Basketball',
  'Football',
  'Soccer',
  'Tennis',
  'Baseball',
  'Hockey',
  'Volleyball',
  'Golf',
  'Swimming',
  'Boxing',
  'Track and field',
  'Cycling',
  'Gymnastics',
  'Wrestling',
  'Skiing',
  'Snowboarding',
  'Surfing',
  'Rowing',
  'Fencing',
  'Badminton',
  'Table tennis',
  'Taekwondo',
  'Judo',
  'Karate',
  'Sailing',
  'Horse racing',
  'Rugby',
  'Cricket',
  'Lacrosse',
  'Ultimate frisbee',
  'Water polo',
  'Handball',
  'Bobsledding',
  'Skeleton',
  'Luge',
  'Shooting',
  'Archery',
  'Weightlifting',
  'Powerlifting',
  'Bodybuilding',
  'Box lacrosse',
  'Field hockey',
  'Polo',
  'Racquetball',
  'Squash',
  'Netball',
  'Kabaddi',
  'Paddleboarding',
  'Triathlon',
  'Duathlon',
  'Decathlon',
  'Heptathlon',
  'Biathlon',
  'Modern pentathlon',
  'Synchronized swimming',
  'Water skiing',
  'Wakeboarding',
  'Barefoot skiing',
  'Freestyle skiing',
  'Cross-country skiing',
  'Alpine skiing',
  'Freestyle snowboarding',
  'Alpine snowboarding',
  'Speed skating',
  'Short track speed skating',
  'Figure skating',
  'Ice dancing',
  'Ice hockey',
  'Beach volleyball',
  'Canoeing',
  'Kayaking',
  'Dragon boat racing',
  'Kiteboarding',
  'Skydiving',
  'Hang gliding',
  'Paragliding',
  'Bungee jumping',
  'Rock climbing',
  'Mountaineering',
  'Caving',
  'Parkour',
  'Street workout',
  'Capoeira',
  'Yoga',
  'Pilates',
  'Zumba',
  'Aerobics',
  'Crossfit',
  'Martial arts',
  'Jiu-jitsu',
  'Muay Thai',
  'Kickboxing',
  'Boxercise',
  'Dancing',
  'Rhythmic gymnastics',
  'Trampoline',
  'Bouldering',
  'Ice climbing',
];
